---

- name: Install basic utils
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    with_items:
      - kitty
      - chromium


- name: Install xorg

- name: Install i3

- name: Configure i3
  template:

- name: Install Ly Display Manager

- name: Install gui tools
