---
- name: Install xorg
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - xorg-server
    - xorg-xinit
    - xorg-xrandr
  become: true

- name: Install i3 metapackages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
      - i3-wm
      - i3lock
  become: true

- name: Install additional packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
      - dunst
      - volumeicon
      - xorg-xsetroot
      - picom
      - xsel
      - rofi
      - rofi-calc
      - scrot
      - viewnior
      - xsettingsd
      - hsetroot
      - lxappearance
      - feh
  become: true

- name: Additional packages from aur
  kewlfft.aur.aur:
    name: "{{ item }}"
  become: true
  become_user: "{{ username }}"
  with_items:
    - themix-full-git
    - polybar
    - nerd-fonts-source-code-pro
    - nerd-fonts-jetbrains-mono

- name: Copy dotfiles
  ansible.builtin.copy:
    src: "{{ item.s }}"
    dest: "{{ item.d }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
  with_items:
      - { s: "files/.config/i3/config", d: "/home/{{username}}/.config/i3/" }
      - { s: "files/.config/dunst/dunstrc" , d: "/home/{{username}}/.config/dunst/" }
      - { s: "files/.config/compton.conf" , d: "/home/{{username}}/.config/" }
      - { s: "files/.Xresources" , d: "/home/{{username}}/" }
      - { s: "files/.xsettingsd" , d: "/home/{{username}}/" }
      - { s: "files/.config/oomox/colors/srcery", d: "/home/{{username}}/.config/oomox/colors/" }
      - { s: "files/.config/procps/toprc", d: "/home/{{username}}/.config/procps/" }
      - { s: "files/.config/kitty/kitty.conf", d: "/home/{{username}}/.config/kitty/" }
      - { s: "files/.config/kitty/srcery_kitty.conf", d: "/home/{{username}}/.config/kitty/" }
      - { s: "files/.config/rofi/srcery_rofi.rasi", d: "/home/{{username}}/.config/rofi/" }
      - { s: "files/.config/rofi/config.rasi", d: "/home/{{username}}/.config/rofi/" }
      - { s: "files/.config/polybar", d: "/home/{{username}}/.config/" }
      - { s: "files/.wallpapers", d: "/home/{{username}}/" }
  become: true

- name: Chmod +x for scripts
  file: dest="{{item}}" mode="ug+x"
  with_items:
    - "/home/{{username}}/.config/polybar/launch.sh"
  become: true

- name: Install Ly Display Manager
  kewlfft.aur.aur:
    name: ly
  become: true
  become_user: "{{ username }}"

- ansible.builtin.systemd:
    name: ly.service
    state: started
    enabled: yes
  become: true

#- name: Install gui tools

- name: Install basic gui utils
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - arandr
    - kitty
    - chromium
    - code
    - keepass
    - firefox
    - gedit
    - calibre
  become: true

- name: Gui utils from aur
  kewlfft.aur.aur:
    name: "{{ item }}"
  become: true
  become_user: "{{ username }}"
  with_items:
    - obsidian