---

- name: Create usergroups
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - wheel
  become: true

- name: Create user
  user:
    name: "{{ username }}"
    password: "{{ userpasshash }}"
    groups: docker,wheel
  become: true

- name: Ensure that wheel is able to use sudo without password
  lineinfile:
    path: /etc/sudoers
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  become: true

- name: Ensure that {{ username }} can run pacman without password
  when: ansible_facts["os_family"]|lower == "archlinux"
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: '{{ username }} ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'
  become: true

- name: Update packages
  when: ansible_facts["os_family"]|lower == "archlinux"
  community.general.pacman:
    update_cache: yes
  become: true

- name: upgrade packages
  when: ansible_facts["os_family"]|lower == "archlinux"
  community.general.pacman:
    upgrade: yes
  become: true

- name: update & upgrade ubuntu
  when: ansible_facts["os_family"]|lower == "debian"
  apt:
    update_cache: yes
    upgrade: yes
  become: true

- name: Install core ubuntu packages
  when: ansible_facts["os_family"]|lower == "debian"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ ubuntu_core_packages|flatten }}"
  become: true

- name: Install core arch packages
  when: ansible_facts["os_family"]|lower == "archlinux"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ arch_core_packages|flatten }}"
  become: true

- name: Check if yay installed
  when: ansible_facts["os_family"]|lower == "archlinux"
  command: 'which yay'
  register: yay_installed
  ignore_errors: yes

- name: Install yay
  when: ansible_facts["os_family"]|lower == "archlinux" and yay_installed.rc != 0 
  shell:
    cmd: |
      pwd
      git clone https://aur.archlinux.org/yay.git /tmp/yay-install
      cd /tmp/yay-install
      makepkg -si --noconfirm
      rm -rf /tmp/yay-install
    executable: /bin/bash
    creates: /usr/bin/yay
  register: log_yay
  become: true
  become_user: "{{username}}"

- assert:
    that:
     - "'error' not in log_yay"

- name: Ubuntu set python3 as default
  when: ansible_facts["os_family"]|lower == "debian"
  alternatives:
    name: python
    link: /usr/bin/python
    path: /usr/bin/python3
  become: true

- name: Install pip packages
  pip:
    name:
     - github3.py
     - requests
    state: latest
  become: true
  become_user: "{{ username }}"

- name: Install network manager & applet
  when: ansible_facts["os_family"]|lower == "archlinux"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - networkmanager
    - network-manager-applet
  become: true
