Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.synced_folder "../", "/home/vagrant/workstation-config/"

  config.vm.provision "shell", inline: "apt install -y python python3 ansible"
end