---

- name: Install TLP
  meta: noop

- name: Configure fingerprint reader
  meta: noop

- name: Install laptop packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - telegram-desktop
    - discord
    - caprine
    - acpi
    - fprintd

- name: Install t480 packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - xf86-video-intel

- name: add to group video
  user:
    name: "{{ username }}"
    group: video
    append: yes
  become: true

- name: create udev rule for backlight setup permission
  become: true
  copy:
    dest: /etc/udev/rules.d/90-backlight.rules
    content: |
      SUBSYSTEM=="backlight", ACTION=="add", \
        RUN+="/bin/chgrp video /sys/class/backlight/%k/brightness", \
        RUN+="/bin/chmod g+w /sys/class/backlight/%k/brightness"

      SUBSYSTEM=="leds", ACTION=="add", KERNEL=="*::kbd_backlight", \
        RUN+="/bin/chgrp video /sys/class/leds/%k/brightness", \
        RUN+="/bin/chmod g+w /sys/class/leds/%k/brightness"

- name: pulse audio manual sink workaround
  become: true
  lineinfile:
    path: /etc/pulse/default.pa
    insertafter: "^#load-module module-pipe-sink"
    line: load-module module-alsa-sink device=hw:0,7

- name: udev hibernate on low battery
  become: true
  copy:
    dest: /etc/udev/rules.d/90-backlight.rules
    content: |
      SUBSYSTEM=="power_supply", ATTR{status}=="Discharging", ATTR{capacity}=="[0-5]", RUN+="/usr/bin/systemctl hibernate"

- name: install bluez
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - bluez
    - bluez-utils