---

- name: Install arch dev packages
  when: ansible_facts["os_family"]|lower == "archlinux"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ arch_dev_packages|flatten }}"
  become: true

- name: Install ubuntu dev packages 
  when: ansible_facts["os_family"]|lower == "debian"
  become: true
  block:
    - name: Install ubuntu apt packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - "{{ ubuntu_dev_packages|flatten }}"

    - name: Install ubuntu snap packages
      snap:
        name: "{{ item }}"
        state: present
        classic: yes
      with_items:
        - "{{ ubuntu_dev_snap_packages }}"