Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.synced_folder "../", "/home/vagrant/workstation-config/"

  config.vm.provision "shell", privileged: false, inline: "echo '[defaults]\nnocows=True\nask_valut_pass=True' > /home/vagrant/.ansible.cfg"
  config.vm.provision "shell", inline: "apt install -y python python3 ansible"

  config.vm.provider "virtualbox" do |vbox|
      vbox.memory = 1024
      vbox.cpus = 1
      vbox.gui = true
      config.disksize.size = "30GB"
  end
end