---

- name: copy config dotfiles
  ansible.builtin.copy:
    src: "{{ item.s }}"
    dest: "{{ item.d }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  become: true
  with_items:
    - { s: "files/.config/i3/config", d: "/home/{{user}}/.config/i3/" }
    - { s: "files/.config/jgmenu", d: "/home/{{user}}/.config/" }
    - { s: "files/.config/conky", d: "/home/{{user}}/.config/" }
    - {
        s: "files/.config/dunst/dunstrc",
        d: "/home/{{user}}/.config/dunst/",
      }
    - { s: "files/.config/picom.conf", d: "/home/{{user}}/.config/" }
    - {
        s: "files/.config/oomox/colors/srcery",
        d: "/home/{{user}}/.config/oomox/colors/",
      }
    - {
        s: "files/.config/procps/toprc",
        d: "/home/{{user}}/.config/procps/",
      }
    - {
        s: "files/.config/kitty/kitty.conf",
        d: "/home/{{user}}/.config/kitty/",
      }
    - {
        s: "files/.config/kitty/srcery_kitty.conf",
        d: "/home/{{user}}/.config/kitty/",
      }
    - { s: "files/.config/alacritty", d: "/home/{{user}}/.config/" }
    - {
        s: "files/.config/rofi/srcery_rofi.rasi",
        d: "/home/{{user}}/.config/rofi/",
      }
    - {
        s: "files/.config/rofi/config.rasi",
        d: "/home/{{user}}/.config/rofi/",
      }
    - { s: "files/.config/polybar", d: "/home/{{user}}/.config/" }
    - { s: "files/.config/ranger", d: "/home/{{user}}/.config" }
    - { s: "files/.config/gtk-3.0", d: "/home/{{user}}/.config" }
    - { s: "files/.config/fontconfig", d: "/home/{{user}}/.config/fontconfig" }
    - { s: "files/.config/Trolltech.conf", d: "/home/{{user}}/.config/" }

- name: Clone ranger_devicons plugin repo
  git:
    repo: https://github.com/alexanderjeurissen/ranger_devicons
    dest: /home/{{ user }}/.config/ranger/plugins/ranger_devicons
  become: true
  become_user: "{{ user }}"

- name: copy home dotfiles
  #when: 0 > 1
  ansible.builtin.copy:
    src: "{{ item.s }}"
    dest: "{{ item.d }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  become: true
  with_items:
    # also freezed
    - { s: "files/.Xresources", d: "/home/{{user}}/" }
    # also freezes?
    - { s: "files/.xsettingsd", d: "/home/{{user}}/" }
    # caused freezes
    - { s: "files/.wallpapers", d: "/home/{{user}}/" }
    # or this 4 freezed
    - { s: "files/.themes", d: "/home/{{user}}" }
    - { s: "files/.gtkrc-2.0", d: "/home/{{user}}/" }

- name: copy icons
  #when: 0 > 1
  ansible.builtin.copy:
    src: "files/.icons"
    dest: "/home/{{user}}/"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  become: true

- name: copy local bin
  ansible.builtin.copy:
    src: "{{ item.s }}"
    dest: "{{ item.d }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  become: true
  with_items:
    - { s: "files/.local/bin", d: "/home/{{user}}/.local/" }

- name: Chmod +x for scripts
  file: dest="{{item}}" mode="ug+x"
  with_items:
    - "/home/{{user}}/.config/polybar/launch.sh"
    - "/home/{{user}}/.local/bin/polybar-popup-calendar.sh"
    - "/home/{{user}}/.local/bin/polybar-script-xidlehook.sh"
    - "/home/{{user}}/.local/bin/rofi-power-menu"
    - "/home/{{user}}/.local/bin/save_dotfiles.sh"
    - "/home/{{user}}/.local/bin/dpms-notifier.sh"
  become: true

- name: Copy root dotfiles
  ansible.builtin.copy:
    src: "{{ item.s }}"
    dest: "{{ item.d }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items:
    - { s: "files/xinitrc", d: "/etc/X11/xinit/" }
  become: true
