---
- name: Install xorg
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - xorg-server
    - xorg-xsetroot
    - xorg-xinit
    - xorg-xrandr
    - xorg-xinput
  become: true

- name: Install i3 metapackages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - i3-gaps
    - i3lock
  become: true

- name: Install additional packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - dunst
    - volumeicon
    - picom
    - xsel
    - rofi
    - rofi-calc
    - scrot
    - viewnior
    - xsettingsd
    - hsetroot
    - lxappearance
    - feh
    - thunar
    - w3m
    - pulseaudio
    - pulseaudio-alsa
    - alsa-utils
    - pavucontrol
    - arandr
    - terminus-font
    - yad
    - xdotool
    - conky
    - clipmenu
    - ttf-nerd-fonts-symbols-2048-em
    - ttf-nerd-fonts-symbols-2048-em-mono
    - jgmenu
    - brightnessctl
    - flameshot
    - perl-anyevent-i3
    - pasystray
    - noto-fonts
    - noto-fonts-cjk
    - noto-fonts-emoji
    - noto-fonts-extra
    - redshift
    - autorandr
    - z
    - qt5ct
    - ueberzug
  become: true

- name: Additional packages from aur
  kewlfft.aur.aur:
    name: "{{ item }}"
  become: true
  become_user: "{{ username }}"
  with_items:
    - themix-full-git
    - polybar
    - qt5-styleplugins
    - qt6gtk2
      

- name: setup home for guest
  include_tasks: home.yml
  vars:
    user: guest

- name: setup home for main user
  include_tasks: home.yml
  vars:
    user: "{{username}}"