# https://github.com/srcery-colors/srcery-terminal/

# Colors (Srcery)
colors:
  # Default colors
  primary:
    background: '#1c1b19'
    foreground: '#fce8c3'

  # Cursor colors
  cursor:
    text: CellBackground
    cursor: '#fbb829'

  # Normal colors
  normal:
    black:   '#1c1b19'
    red:     '#ef2f27'
    green:   '#519f50'
    yellow:  '#fbb829'
    blue:    '#2c78bf'
    magenta: '#e02c6d'
    cyan:    '#0aaeb3'
    white:   '#baa67f'

  # Bright colors
  bright:
    black:   '#918175'
    red:     '#f75341'
    green:   '#98bc37'
    yellow:  '#fed06e'
    blue:    '#68a8e4'
    magenta: '#ff5c8f'
    cyan:    '#2be4d0'
    white:   '#fce8c3'

scrolling:
  history: 10000
  tabspaces: 2
  multiplier: 3

window:
  padding:
    x: 1
    y: 2
  dunamic_padding: true
  decorations: none

font:
  normal:
    family: Terminus
    style: Regular
  size: 14.0

live_config_reload: true

env:
  WINIT_X11_SCALE_FACTOR: "1"