---

- name: Install tmux
  package:
    name: tmux
    state: present
  become: true

- name: Copy config
  copy:
    src: files/.tmux.conf
    dest: /home/{{user}}/.tmux.conf
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0640
  become: true

- name: Check if tpm is installed
  stat:
    path: /home/{{user}}/.tmux/plugins/tpm
  register: tpm_dir
  become: true
  become_user: "{{ user }}"

- name: Install tpm
  when: not (tpm_dir.stat.exists and tpm_dir.stat.isdir)
  git:
    repo: "https://github.com/tmux-plugins/tpm.git"
    dest: /home/{{user}}/.tmux/plugins/tpm
  become: true
  become_user: "{{ user }}"
