---

- name: Install vim
  package:
    name: "{{ vim_package[ansible_os_family] }}"
    state: present
  become: true

- name: Copy config
  copy:
    src: files/.vimrc
    dest: /home/{{username}}/.vimrc
    owner: "{{username}}"
    group: "{{username}}"
    mode: 0640
  become: true

- name: Check if vim-plug is installed
  stat:
    path: /home/{{username}}/.vim/autoload/plug.vim
  register: plug_file
  become: true
  become_user: "{{ username }}"

- name: Install vim-plug
  when: not (plug_file.stat.exists)
  shell:
    cmd: |
      curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    executable: /usr/bin/zsh
  become: true
  become_user: "{{ username }}"
