---

- name: Install vim
  package:
    name: vim
    state: present
  become: true

- name: Copy config
  template:
    src: templates/vimrc.j2
    dest: /home/{{username}}/.vimrc.conf
    owner: "{{username}}"
    group: "{{username}}"
    mode: 0640
  become: true
