---

- name: Install zsh
  package:
    name: zsh
    state: present
  become: true

- name: Copy config
  copy:
    src: files/.zshrc
    dest: /home/{{username}}/.zshrc
    owner: "{{username}}"
    group: "{{username}}"
    mode: 0640
  become: true

# Just .config dir for now, TODO remove with_items
- name: copy additional configuration files 
  copy: 
    src: "{{ item.s }}"
    dest: "{{ item.d }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
  with_items:
    - { s: "files/.config/", d: "/home/{{username}}/.config/" }
  become: true

- name: Set user default shell to zsh
  user:
    name: "{{ username }}"
    shell: /usr/bin/zsh
  become: true

- name: Check if zplug is installed
  stat:
    path: /home/{{username}}/.zplug
  register: zplug_dir
  become: true
  become_user: "{{ username }}"

- name: Find zplug latest release
  github_release:
    user: zplug
    repo: zplug
    action: latest_release
  become: true
  become_user: "{{ username }}"

# TODO change zplug to something reasonably fast
- name: Install zplug
  when: not (zplug_dir.stat.exists and zplug_dir.stat.isdir)
  git:
    repo: "https://github.com/zplug/zplug.git"
    dest: /home/{{username}}/.zplug
  become: true
  become_user: "{{ username }}"
