---

- name: Install zsh
  become: true
  package:
    name: zsh
    state: present

- name: Copy config
  become: true
  copy:
    src: files/.zshrc
    dest: /home/{{username}}/.zshrc
    owner: "{{username}}"
    group: "{{username}}"
    mode: 0640

# Just .config dir for now, TODO remove with_items
- name: copy additional configuration files 
  become: true
  copy: 
    src: "{{ item.s }}"
    dest: "{{ item.d }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
  with_items:
    - { s: "files/.config/", d: "/home/{{username}}/.config/" }

- name: Set user default shell to zsh
  become: true
  user:
    name: "{{ username }}"
    shell: /usr/bin/zsh

- name: Install antigen arch
  when: ansible_facts["os_family"] == "Archlinux"
  become: true
  become_user: "{{ username }}"
  kewlfft.aur.aur:
    name: antigen-git
  
- name: Install antigen ubuntu
  when: ansible_facts["os_family"] == "Debian"
  become: true
  package:
    name: zsh-antigen
    state: present

- name: create symlink for antigen.zsh
  when: ansible_facts["os_family"] == "Debian"
  become: true
  block:
    - file:
        dest: /usr/share/zsh/share
        state: directory
    - file: 
        src: /usr/share/zsh-antigen/antigen.zsh
        dest: /usr/share/zsh/share/antigen.zsh
        state: link
        force: yes
    